import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// Add Free Font Awesome Icons
// https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=solid&m=free
// In order to add an icon, you have to:
// 1) add the icon name in the import statement below;
// 2) add the icon name to the library.add() statement below.
import {
    faArrowAltCircleUp,
    faCog,
    faEdit,
    faEye,
    faEyeSlash,
    faList,
    faPause,
    faPlay,
    faPlus,
    faSearch,
    faTachometerAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faCheckCircle,
    faStream,
    faSave,
    faExclamationCircle,
    faBullhorn,
    faArrowsAltV,
    faBell,
    faUnlink,
    faQuestionCircle,
    faImages,
    faUpload,
    faCopy,
    faCheck,
    faFile,
    faAward,
    faLink,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faChevronDown,
    faSignOutAlt,
    faPen,
    faExternalLinkSquareAlt,
    faSpinner,
    faUndo,
    faPlusCircle,
    faAngleDown,
    faWrench,
    faHeartbeat,
    faFilter,
    faInfoCircle,
    faClone,
    faCertificate,
    faSun,
    faMoon,
    faDesktop,
    // v2 additions — keep icon names v5-compatible, the project's
    // `~5.15.4` install doesn't have v6-renamed names like
    // `house` / `screwdriver-wrench` / `rotate-left` / `sliders`.
    faBars,
    faTools,
    faHome,
    faSlidersH,
    faCircle,
    faGlobe,
    faPlug,
    faWifi,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faArrowAltCircleUp,
    faCog,
    faEdit,
    faEye,
    faEyeSlash,
    faList,
    faPause,
    faPlay,
    faPlus,
    faSearch,
    faTachometerAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faCheckCircle,
    faStream,
    faSave,
    faExclamationCircle,
    faBullhorn,
    faArrowsAltV,
    faBell,
    faUnlink,
    faQuestionCircle,
    faImages,
    faUpload,
    faCopy,
    faCheck,
    faFile,
    faAward,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faChevronDown,
    faSignOutAlt,
    faPen,
    faExternalLinkSquareAlt,
    faSpinner,
    faUndo,
    faPlusCircle,
    faAngleDown,
    faLink,
    faWrench,
    faHeartbeat,
    faFilter,
    faInfoCircle,
    faClone,
    faCertificate,
    faSun,
    faMoon,
    faDesktop,
    faBars,
    faTools,
    faHome,
    faSlidersH,
    faCircle,
    faGlobe,
    faPlug,
    faWifi,
);

export { FontAwesomeIcon };

